<?php

function ads_perm(){

return array('access ads list page');
}

function ads_menu(){
$items['ads/list'] = array(
	'page callback' => 'ads_list_view',
	'access arguments' => array('access ads list page'),
	'type' => MENU_NORMAL_ITEM,
	);
$items['admin/settings/ads'] = array(
    'title' => t('ADs module settings'),
    'description' => t('Description of your ADs settings page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ads_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );
	
	return $items;
}


function ads_list_view(){
$node = node_load(array("nid" => $nid));
$page_content = print_r($node);
return $page_content;
}

function ads_admin(){
$form = array();

  $form['ads_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('ads_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,
  );
  
  $form['ads_maxdis'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('ads_maxdis', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);

}
